service: notification-service

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  timeout: 60
  deploymentMethod: direct

functions:
  notificationFunction:
    handler: index.handler

plugins:
  - serverless-offline
  
resources:
  Outputs:
    NotificationTopicArn:
      Value: {"Ref": "NotificationTopic"}
      Export:
        Name: NotificationTopicArn

  Resources:
    NotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Notification Topic
        TopicName: notification-topic